//CUCUMBER
browser = Chrome
url = https://www.naukri.com/
username = sakkaiyank30@gmail.com
userpassword = SMSM3010
ReasumeHeadline = i have 4 year experience in software testing
Enterskills = Cucumber Testing
universityname = Madurai Kamaraj University, Madurai